name = "myphone-app"
compatibility_date = "2024-07-25"
pages_build_output_dir = "dist"

[env.production]
name = "myphone-app"

[build]
command = "npm run build"

[build.environment_variables]
NODE_VERSION = "18"